name: Deploy VPN

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Sing-box
      run: |
        wget https://github.com/SagerNet/sing-box/releases/download/v1.8.0/sing-box-1.8.0-linux-amd64.tar.gz
        tar -xvzf sing-box-1.8.0-linux-amd64.tar.gz
        cd sing-box-1.8.0-linux-amd64
        chmod +x sing-box
        sudo mv sing-box /usr/local/bin/

    - name: Create config.json
      run: |
        mkdir -p ~/.singbox
        cat <<EOF > ~/.singbox/config.json
        {
          "log": {
            "level": "info",
            "output": "stdout"
          },
          "inbounds": [
            {
              "type": "vless",
              "listen": "0.0.0.0",
              "listen_port": 443,
              "users": [
                {
                  "uuid": "1fb38348-70a9-4265-9337-0deaf5e323f7",
                  "flow": ""
                }
              ],
              "tls": {
                "enabled": true,
                "server_name": "aminvpn.duckdns.org"
              },
              "transport": {
                "type": "ws",
                "path": "/digikala.com/login"
              }
            }
          ],
          "outbounds": [
            {
              "type": "direct"
            }
          ]
        }
        EOF

    - name: Start VPN (for test)
      run: |
        nohup sing-box run -c ~/.singbox/config.json &
        sleep 10
